/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as SelectCompanyRouteImport } from './routes/select-company'
import { Route as AlertsIndexRouteImport } from './routes/alerts.index'
import { Route as CompetitorsIndexRouteImport } from './routes/competitors.index'
import { Route as CompetitorsRetailerIdRouteImport } from './routes/competitors.$retailerId'
import { Route as ProductRetailerIdProductIdRouteImport } from './routes/product.$retailerId.$productId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const SelectCompanyRoute = SelectCompanyRouteImport.update({
  id: '/select-company',
  path: '/select-company',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertsIndexRoute = AlertsIndexRouteImport.update({
  id: '/alerts/',
  path: '/alerts/',
  getParentRoute: () => rootRouteImport,
} as any)
const CompetitorsIndexRoute = CompetitorsIndexRouteImport.update({
  id: '/competitors/',
  path: '/competitors/',
  getParentRoute: () => rootRouteImport,
} as any)
const CompetitorsRetailerIdRoute = CompetitorsRetailerIdRouteImport.update({
  id: '/competitors/$retailerId',
  path: '/competitors/$retailerId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductRetailerIdProductIdRoute =
  ProductRetailerIdProductIdRouteImport.update({
    id: '/product/$retailerId/$productId',
    path: '/product/$retailerId/$productId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/select-company': typeof SelectCompanyRoute
  '/competitors/$retailerId': typeof CompetitorsRetailerIdRoute
  '/alerts/': typeof AlertsIndexRoute
  '/competitors/': typeof CompetitorsIndexRoute
  '/product/$retailerId/$productId': typeof ProductRetailerIdProductIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/select-company': typeof SelectCompanyRoute
  '/competitors/$retailerId': typeof CompetitorsRetailerIdRoute
  '/alerts': typeof AlertsIndexRoute
  '/competitors': typeof CompetitorsIndexRoute
  '/product/$retailerId/$productId': typeof ProductRetailerIdProductIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/select-company': typeof SelectCompanyRoute
  '/competitors/$retailerId': typeof CompetitorsRetailerIdRoute
  '/alerts/': typeof AlertsIndexRoute
  '/competitors/': typeof CompetitorsIndexRoute
  '/product/$retailerId/$productId': typeof ProductRetailerIdProductIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/select-company'
    | '/competitors/$retailerId'
    | '/alerts/'
    | '/competitors/'
    | '/product/$retailerId/$productId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/select-company'
    | '/competitors/$retailerId'
    | '/alerts'
    | '/competitors'
    | '/product/$retailerId/$productId'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/dashboard'
    | '/select-company'
    | '/competitors/$retailerId'
    | '/alerts/'
    | '/competitors/'
    | '/product/$retailerId/$productId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  DashboardRoute: typeof DashboardRoute
  SelectCompanyRoute: typeof SelectCompanyRoute
  CompetitorsRetailerIdRoute: typeof CompetitorsRetailerIdRoute
  AlertsIndexRoute: typeof AlertsIndexRoute
  CompetitorsIndexRoute: typeof CompetitorsIndexRoute
  ProductRetailerIdProductIdRoute: typeof ProductRetailerIdProductIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/select-company': {
      id: '/select-company'
      path: '/select-company'
      fullPath: '/select-company'
      preLoaderRoute: typeof SelectCompanyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alerts/': {
      id: '/alerts/'
      path: '/alerts'
      fullPath: '/alerts/'
      preLoaderRoute: typeof AlertsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/competitors/': {
      id: '/competitors/'
      path: '/competitors'
      fullPath: '/competitors/'
      preLoaderRoute: typeof CompetitorsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/competitors/$retailerId': {
      id: '/competitors/$retailerId'
      path: '/competitors/$retailerId'
      fullPath: '/competitors/$retailerId'
      preLoaderRoute: typeof CompetitorsRetailerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$retailerId/$productId': {
      id: '/product/$retailerId/$productId'
      path: '/product/$retailerId/$productId'
      fullPath: '/product/$retailerId/$productId'
      preLoaderRoute: typeof ProductRetailerIdProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  DashboardRoute: DashboardRoute,
  SelectCompanyRoute: SelectCompanyRoute,
  CompetitorsRetailerIdRoute: CompetitorsRetailerIdRoute,
  AlertsIndexRoute: AlertsIndexRoute,
  CompetitorsIndexRoute: CompetitorsIndexRoute,
  ProductRetailerIdProductIdRoute: ProductRetailerIdProductIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
